global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "backend-dev"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "backend:8080" ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: "node-exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "mysql-exporter"
    static_configs:
      - targets: [ "mysqld-exporter:9104" ]

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
