spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000 # 커넥션 타임아웃 30초
      initialization-fail-timeout: -1 # 초기화 실패 시 무한 대기
      maximum-pool-size: 30 # 커넥션 풀 사이즈
      minimum-idle: 10 # 최소 아이들 커넥션
      idle-timeout: 300000 # idle 커넥션 유지 시간 (5분)
      max-lifetime: 1800000 # 커넥션 최대 수명 (30분)

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: false
      hibernate:
        show_sql: false
        format_sql: false

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  scheduler:
    retention-days: 7   # 세션/스트리머 집계 시 기준이 되는 지난 날 수
    batch-size: 1000     # 페이지당 처리할 데이터 개수
    cron: "0 0 12 * * *" # 크론 표현식

  viewer-threshold: 10

logging:
  level:
    root: warn
    com.streampulse.backend: info
    org.springframework: warn
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    com.zaxxer.hikari: warn
    org.springframework.data.redis.connection: warn
    io.lettuce.core: warn

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

processor:
  url: ${PROCESSOR_BASE_URL}