spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000 # 커넥션 타임아웃 30초
      initialization-fail-timeout: -1 # 초기화 실패 시 무한 대기
      maximum-pool-size: 10 # 커넥션 풀 사이즈, 기본 10
      minimum-idle: 2 # 최소 아이들 커넥션
      idle-timeout: 300000 # idle 커넥션 유지 시간 (5분)
      max-lifetime: 1800000 # 커넥션 최대 수명 (30분)

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    org.hibernate.orm.jdbc.bind: warn

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

processor:
  url: ${PROCESSOR_BASE_URL}