spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  #      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#            database.action: none

  data:
    redis:
      host: localhost
      #      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  viewer-threshold: 100

logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    org.hibernate.orm.jdbc.bind: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"

processor:
  url: ${PROCESSOR_BASE_URL}