spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL}

chzzk:
  api-base-url: ${CHZZK_API_BASE_URL}
  client-id: ${CHZZK_CLIENT_ID}
  client-secret: ${CHZZK_CLIENT_SECRET}

openai:
  api:
    key: ${OPENAI_API_KEY}