spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    org.hibernate.orm.jdbc.bind: warn

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

processor:
  url: ${PROCESSOR_BASE_URL}