spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: false
      hibernate:
        show_sql: false
        format_sql: false
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql

  data:
    redis:
#      host: localhost
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  scheduler:
    retention-days: 7   # 세션/스트리머 집계 시 기준이 되는 지난 날 수
    batch-size: 1000     # 페이지당 처리할 데이터 개수
    cron: "0 * * * * *" # 크론 표현식

  viewer-threshold: 100

logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.hibernate.orm.jdbc.bind: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

processor:
  url: ${PROCESSOR_BASE_URL}

