services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ../../.env.prod
    volumes:
      - ../../logs/prod:/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - app-network
      - monitoring-network
    command: ["sh", "-c", "java $$JAVA_OPTS -jar /app/streampulse.jar"]
    restart: always
    depends_on:
      - processor

  processor:
    build:
      context: ../../processor
      dockerfile: Dockerfile.prod
    container_name: processor
    ports:
      - "3001:3001"
    env_file:
      - ../../.env.prod
    volumes:
      - ../../logs/prod:/logs
    networks:
      - app-network
    command: [ "node", "index.js" ]
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitoring-network

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ../../logs/prod:/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    networks:
      - monitoring-network

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - monitoring-network

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    ports:
      - "9104:9104"
    env_file:
      - ../../.env.prod
    networks:
      - monitoring-network
    restart: always


networks:
  app-network:
    driver: bridge
  monitoring-network:
    driver: bridge

volumes:
  grafana-storage:
