name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create secret files locally
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env
          echo "${{ secrets.CREDENTIALS_JSON_B64 }}" | base64 --decode > credentials.json

      - name: Send secret files to GCP VM
        run: |
          scp -o StrictHostKeyChecking=no .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/jyhun/StreamPulse/infra/prod/.env
          scp -o StrictHostKeyChecking=no credentials.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/jyhun/StreamPulse/infra/prod/credentials.json

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd /home/jyhun/StreamPulse
            git pull origin main
            mkdir -p infra/prod
            docker compose -f infra/prod/docker-compose.yml build --no-cache --pull
            docker compose -f infra/prod/docker-compose.yml down
            docker compose -f infra/prod/docker-compose.yml up -d
          EOF

      - name: Health Check
        run: |
          sleep 10
          curl -f http://${{ secrets.SSH_HOST }}:8080/health || exit 1
